task_type = "text2music"
config_path = "acestep-v15-turbo"
duration = 60.0
inference_steps = 8
seed = -1
use_random_seed = true
batch_size = 1
thinking = true
use_cot_metas = true
use_cot_caption = false
use_cot_lyrics = false
use_cot_language = false
use_constrained_decoding = false
sample_mode = false
use_format = false
lm_temperature = 0.85
lm_top_k = 0
lm_top_p = 0.95
lm_cfg_scale = 2.8
guidance_scale = 7.0
shift = 3.0
infer_method = "ode"
sampler_mode = "heun"
use_adg = false
cfg_interval_start = 0.0
cfg_interval_end = 1.0
velocity_norm_threshold = 1.6
velocity_ema_factor = 0.05
offload_to_cpu = true
offload_dit_to_cpu = false
device = "auto"
backend = "pt"
audio_format = "mp3"
vae = "scragvae"
lm_model_path = "acestep-5Hz-lm-0.6B"
lm_negative_prompt = "low quality, noise"
bpm = 95
keyscale = "B Minor"
instrumental = false
vocal_language = "es"
lyrics = "baila, baila conmigo\ndale, dale, dale"
caption = "Catchy reggaeton with a bouncy dembow rhythm, deep punchy bass, bright synth plucks, summery melodic hooks, energetic and danceable, Latin club anthem."
